### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by biw** [GuildEducationInc/webpacker_ssr-react#1]
First of all thanks for the great project!

Both https://github.com/GuildEducationInc/webpacker_ssr & https://github.com/GuildEducationInc/webpacker_ssr-execjs have MIT licenses and I noticed this doesn't have one. I would be happy to open up a pull request to add one, just wanted to check to see if that would be okay?

**Comment by wingrunr21** [comment]
Sure! Thanks for catching that!

**Comment by biw** [comment]
Closing because there is a LICENSE 🤦🏻‍♂️
